# Generated by Django 4.1.4 on 2023-01-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='album_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('album_date', models.DateTimeField()),
                ('album_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='photo_album_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=150)),
                ('photo_description', models.CharField(max_length=150)),
                ('photo_date', models.DateTimeField()),
                ('photo_1', models.ImageField(upload_to='uploads/')),
                ('photo_3', models.ImageField(upload_to='uploads/')),
                ('photo_4', models.ImageField(upload_to='uploads/')),
                ('photo_5', models.ImageField(upload_to='uploads/')),
                ('photo_6', models.ImageField(upload_to='uploads/')),
                ('photo_7', models.ImageField(upload_to='uploads/')),
                ('photo_8', models.ImageField(upload_to='uploads/')),
                ('photo_9', models.ImageField(upload_to='uploads/')),
                ('photo_10', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
