# Generated by Django 4.1.4 on 2023-01-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventForm',
            fields=[
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mobile_number', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('permenant_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='smallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_descripton', models.CharField(max_length=150)),
                ('event_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
