# Generated by Django 4.1.4 on 2023-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventform',
            name='city',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='eventform',
            name='date_of_birth',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='eventform',
            name='event_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='eventform',
            name='gender',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='eventform',
            name='mother_tongue',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Hindi', max_length=100),
        ),
        migrations.AddField(
            model_name='eventform',
            name='postal_code',
            field=models.IntegerField(default='000000'),
        ),
        migrations.AddField(
            model_name='eventform',
            name='state',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Maharashtra', max_length=100),
        ),
    ]
