# Generated by Django 4.1.4 on 2023-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0003_alter_eventform_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='date_of_birth',
            field=models.CharField(default='02/12/1990', max_length=10),
        ),
    ]
