# Generated by Django 4.1.4 on 2023-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0004_alter_eventform_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='mobile_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='permenant_address',
            field=models.TextField(max_length=500),
        ),
    ]
