# Generated by Django 4.1.4 on 2023-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0006_alter_eventform_city_alter_eventform_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventform',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
