# Generated by Django 4.1.4 on 2023-01-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0007_eventform_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallevent',
            name='location',
            field=models.CharField(default='Pune', max_length=150),
        ),
        migrations.AlterField(
            model_name='smallevent',
            name='event_descripton',
            field=models.CharField(max_length=900),
        ),
    ]
